modLoader="javafml"
loaderVersion="[4,)"
license="${mod_license}"

[[mods]]
modId="universaldraconicslots"
version="${mod_version}"
displayName="Universal Draconic Slots"
authors="LikeAzusa2"
description='''
Adds Draconic Evolution module host support to compatible non-DE equipment.
'''

[[dependencies.universaldraconicslots]]
modId="neoforge"
mandatory=true
versionRange="[21.1.72,)"
ordering="NONE"
side="BOTH"

[[dependencies.universaldraconicslots]]
modId="draconicevolution"
mandatory=true
versionRange="[3.1.4.632,)"
ordering="AFTER"
side="BOTH"

[[dependencies.universaldraconicslots]]
modId="brandonscore"
mandatory=true
versionRange="[3.2.1.307,)"
ordering="AFTER"
side="BOTH"

[[dependencies.universaldraconicslots]]
modId="codechickenlib"
mandatory=true
versionRange="[4.6.1.524,)"
ordering="AFTER"
side="BOTH"

[[dependencies.universaldraconicslots]]
modId="curios"
mandatory=true
versionRange="[9.5.1+1.21.1,)"
ordering="AFTER"
side="BOTH"

[[mixins]]
config="mixins/universaldraconicslots.json"
